# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Nathan/Documents/GitHub/AMDC-Firmware3/project_zedboard_1/project_zedboard_1.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0.xci
# IP: The module: 'base_zynq_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nathan/Documents/GitHub/AMDC-Firmware3/project_zedboard_1/project_zedboard_1.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Nathan/Documents/GitHub/AMDC-Firmware3/project_zedboard_1/project_zedboard_1.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0.xci
# IP: The module: 'base_zynq_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nathan/Documents/GitHub/AMDC-Firmware3/project_zedboard_1/project_zedboard_1.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
