# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/base_zynq/base_zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq || ORIG_REF_NAME==base_zynq} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_axi_gpio_0_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_0_0 || ORIG_REF_NAME==base_zynq_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_0/base_zynq_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xbar_0 || ORIG_REF_NAME==base_zynq_xbar_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_ps7_0_axi_periph_0/base_zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==base_zynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_ece751_h264_enc_0_0/base_zynq_ece751_h264_enc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_ece751_h264_enc_0_0 || ORIG_REF_NAME==base_zynq_ece751_h264_enc_0_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_auto_pc_2/base_zynq_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_2 || ORIG_REF_NAME==base_zynq_auto_pc_2} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_0 || ORIG_REF_NAME==base_zynq_auto_pc_0} -quiet] -quiet

# IP: bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_1 || ORIG_REF_NAME==base_zynq_auto_pc_1} -quiet] -quiet

# XDC: bd/base_zynq/base_zynq_ooc.xdc
